<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-GQIBK4DL" failures="1" tests="2" name="Ecommerce Form Error validations" time="34.919" errors="0" timestamp="2024-03-16T18:35:43 IST">
  <testcase classname="org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example" name="LoginFormErrorValidation" time="12.21"/>
  <testcase classname="org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example" name="LoginFormErrorValidation" time="8.797">
    <failure type="java.lang.AssertionError" message="expected [Please enter your nme] but found [Please enter your name]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your nme] but found [Please enter your name]
at org.internal.pageObjects.android.FormPage.validateToastMessage(FormPage.java:67)
at org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example.LoginFormErrorValidation(eCommerce_Data_Driven_Testing_Via_DataProvider_Example.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- LoginFormErrorValidation -->
</testsuite> <!-- Ecommerce Form Error validations -->
