<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-16T18:34:55 IST" name="Suite" finished-at="2024-03-16T18:35:43 IST" duration-ms="47328">
    <groups>
      <group name="Smoke">
        <method signature="eCommerce_Data_Driven_Testing_Via_DataProvider_Example.LoginFormErrorValidation(java.util.HashMap)[pri:0, instance:org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example@97e93f1]" name="LoginFormErrorValidation" class="org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2024-03-16T18:34:55 IST" name="Ecommerce End to End Test" finished-at="2024-03-16T18:35:07 IST" duration-ms="12019">
      <class name="org.internal.eCommerce_Tc_1">
        <test-method is-config="true" signature="ConfigureAppium()[pri:0, instance:org.internal.eCommerce_Tc_1@28dcca0c]" started-at="2024-03-16T18:34:55 IST" name="ConfigureAppium" finished-at="2024-03-16T18:35:07 IST" duration-ms="11607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureAppium -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:org.internal.eCommerce_Tc_1@28dcca0c]" started-at="2024-03-16T18:35:07 IST" name="TearDown" finished-at="2024-03-16T18:35:07 IST" duration-ms="397" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- org.internal.eCommerce_Tc_1 -->
    </test> <!-- Ecommerce End to End Test -->
    <test started-at="2024-03-16T18:35:08 IST" name="Ecommerce Form Error validations" finished-at="2024-03-16T18:35:43 IST" duration-ms="34919">
      <class name="org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example">
        <test-method is-config="true" signature="ConfigureAppium()[pri:0, instance:org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example@97e93f1]" started-at="2024-03-16T18:35:08 IST" name="ConfigureAppium" finished-at="2024-03-16T18:35:18 IST" duration-ms="10040" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureAppium -->
        <test-method is-config="true" signature="preSetup()[pri:0, instance:org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example@97e93f1]" started-at="2024-03-16T18:35:18 IST" name="preSetup" finished-at="2024-03-16T18:35:18 IST" duration-ms="121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method signature="LoginFormErrorValidation(java.util.HashMap)[pri:0, instance:org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example@97e93f1]" started-at="2024-03-16T18:35:18 IST" name="LoginFormErrorValidation" data-provider="getData" finished-at="2024-03-16T18:35:30 IST" duration-ms="12210" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{name=Ritu, country=Austria, gender=female, formToastMessage=Please enter your name}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFormErrorValidation -->
        <test-method is-config="true" signature="preSetup()[pri:0, instance:org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example@97e93f1]" started-at="2024-03-16T18:35:32 IST" name="preSetup" finished-at="2024-03-16T18:35:32 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method signature="LoginFormErrorValidation(java.util.HashMap)[pri:0, instance:org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example@97e93f1]" started-at="2024-03-16T18:35:32 IST" name="LoginFormErrorValidation" data-provider="getData" finished-at="2024-03-16T18:35:41 IST" duration-ms="8797" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{name=Rakesh, country=Australia, gender=male, formToastMessage=Please enter your nme}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please enter your nme] but found [Please enter your name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please enter your nme] but found [Please enter your name]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.internal.pageObjects.android.FormPage.validateToastMessage(FormPage.java:67)
at org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example.LoginFormErrorValidation(eCommerce_Data_Driven_Testing_Via_DataProvider_Example.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFormErrorValidation -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example@97e93f1]" started-at="2024-03-16T18:35:42 IST" name="TearDown" finished-at="2024-03-16T18:35:43 IST" duration-ms="617" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- org.internal.eCommerce_Data_Driven_Testing_Via_DataProvider_Example -->
    </test> <!-- Ecommerce Form Error validations -->
  </suite> <!-- Suite -->
</testng-results>
